apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
data:
  ME_CONFIG_MONGODB_URL: "mongodb://chat-mongo-0.chat-mongo-service.chat.svc.cluster.local:27017"
  ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
